blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('users/', include('users.urls')),
]

homepage/urls.py
from django.urls import path
from . import views 

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('new_topic/', views.new_topic, name='new_topic'),
    #path('article/', views.article, name='article'),
    #path('<int:entry_id>/edit_entry/', views.edit_entry, name='edit_entry'),
    path('<int:the_id>/new_entry/', views.new_entry, name='new_entry'),
    path('topic/<int:t_id>/', views.entry, name='entry'),
]

users/urls.py
from django.urls import path
from . import views 

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('profile/', views.profile, name='profile'),
    path('<username>/', views.doneprofile, name='doneprofile'),
]

homepage/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.
class Topic(models.Model):
    GEN_TYPE = [
        ('FASHION','Fashion'),
        ('TECHNOLOGY','Technology'),
        ('EDUCATION','Education'),
        ('FINANCE','Finance'),
        ('LIFESTYLE','Lifestyle'),
        ('OTHER','Other'),
    ]
    title = models.CharField(max_length=190)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    genre = models.CharField(max_length=190, choices=GEN_TYPE)
    

    def __str__(self):
        return self.title

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text 

users/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User 
# Create your models here.

class Profile(models.Model):
    GEN = [
        ('FASHION','Fashion'),
        ('TECHNOLOGY','Technology'),
        ('EDUCATION','Education'),
        ('FINANCE','Finance'),
        ('LIFESTYLE','Lifestyle'),
        ('OTHER','Other'),
    ]
    person = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField(default=13, validators=[MinValueValidator(13)])
    description = models.TextField()
    genre = models.CharField(max_length=40, choices=GEN)

    def __str__(self):
        return self.description

homepage/forms.py
from django import forms 
from django.forms import  Textarea, inlineformset_factory
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic 
        fields = '__all__'

        widgets = {
            'author' : forms.TextInput(attrs={'type':'hidden'}),
        }

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry 
        fields = '__all__'

        widgets = {
            'topic' : forms.TextInput(attrs={'type':'hidden','style':'width: 5em'}),
        }

    

users/forms.py
from django import forms
from .models import Profile 

class SignUpForm(forms.Form):
    firstname = forms.CharField(max_length=190)
    lastname = forms.CharField(max_length=190)
    username = forms.CharField(max_length=190)
    password = forms.CharField(widget=forms.PasswordInput)


class SignInForm(forms.Form):
    username = forms.CharField(max_length=190)
    password = forms.CharField(widget=forms.PasswordInput)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['person', 'age', 'description', 'genre']

        widgets = {
            'person' : forms.TextInput(attrs={'type':'hidden'}),
        }

    

        

homepage/views.py
from django.shortcuts import render, redirect 
from django.forms import inlineformset_factory
from django.contrib.auth.models import User 
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
# Create your views here.

def home(request):
    topics = Topic.objects.all()
    context = {'topics': topics}
    return render(request, 'homepage/home.html', context)

def entry(request, t_id):
    topics = Topic.objects.get(id=t_id)
    texts = topics.entry_set.all()
    context = {'texts':texts}
    return render(request, 'homepage/entry.html', context)

def new_topic(request):
    if request.method != 'POST': 
        form = TopicForm({'author': request.user.id} or None) 
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:new_entry')
    context = {'form':form}
    return render(request, 'homepage/postform.html', context)

def new_entry(request, the_id):
    topic = Topic.objects.get(id=the_id)
    if request.method != 'POST': 
        form = EntryForm({'topic': topic.id})
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:home')
    context = {'form':form, 'topic':topic}
    return render(request, 'homepage/new_entry.html', context)

users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User 
from homepage.models import Topic
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, SignInForm, ProfileForm
from .models import Profile
# Create your views here.
def signup(request):
    if request.method != 'POST':
        form = SignUpForm()
    else:
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        username = request.POST['username']
        password = request.POST['password']
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = User.objects.create_user(first_name=firstname, last_name=lastname, username=username, password=password)
            user.save()
            return redirect('users:signin')
        else:
            return reverse('users:signup')
    context = {'form': form}
    return render(request, 'users/signup.html', context)

def signin(request):
    if request.method != 'POST':
        form = SignInForm()
    else:
        username = request.POST['username']
        password = request.POST['password']
        form = SignInForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('users:profile')
            else:
                form = SignInForm(data=form.errors)
        else:
            raise Http404
    context = {'form': form}
    return render(request, 'users/signin.html', context)

def signout(request):
    logout(request)
    return render(request, 'users/success.html')

def profile(request):
    if request.method != 'POST':
        form = ProfileForm({'person':request.user.id})
    else:
        form = ProfileForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:home')
    context = {'form': form}
    return render(request, 'users/profile.html', context)

def doneprofile(request, username):
    userprofile = User.objects.get(username=username)
    profiles = userprofile.profile
    context = {'userprofile': userprofile, 'profiles':profiles}
    return render(request, 'users/myprofile.html', context)

homepage/templates/homepage/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} Base Templates{% endblock title %}</title>
</head>
<body>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <header>{% block header %}{% endblock header %}</header>
    <article>
    {% block content %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
        
    {% endblock content %}</article>
</body>
</html>

homepage/templates/homepage/entry.html
{% extends 'homepage/base.html' %}
{% block title %} Entry {% endblock title %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">Blogger</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
</button>
{% endblock header %}
{% block content %}

    {% for text in texts %}
    <ul class="list-group" style="text-align: center;">
        <li class="list-group-item">{{text}}</li>
    </ul>
    {% empty %}
    <ul class="list-group" style="text-align: center;">
        <li class="list-group-item">There are no entries</li>
    </ul>
    
    {% endfor %}


{% endblock content %}

homepage/templates/homepage/home.html
{% extends 'homepage/base.html' %}
{% block title %} Blogger {% endblock title %}

{% block header %}

{% if user.is_active %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">Blogger</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'homepage:new_topic' %}">Add a Topic <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:signout' %}">Sign Out</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:doneprofile' user.username %}">Profile Page</a>
        </li>
      </ul>
    </div>
  </nav>

{% else %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">Blogger</a> 
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'users:signup' %}">Sign Up<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:signin' %}">Sign In</a>
            </li>
          </ul>
        </div>
      </nav>
    {% endif %}
{% endblock header %}
{% block content %}
{% for topic in topics %}
<div class="list-inline text-center">
    <a href="{% url 'homepage:entry' topic.id %}" class="list-group-item list-group-item-action">{{topic}}</a>
  </div>
{% endfor %}

{% endblock content %}

homepage/templates/homepage/new_entry.html
{% extends 'homepage/base.html' %}

{% block header %}
<p>
    <h3><a href="{% url 'homepage:home' %}">homepage</a> - 
    <a href="{% url 'homepage:new_topic' %}">back to topics </a> - Add an Entry </h3>
</p>

{% endblock header %}

{% block content %}
{% if user.is_active  %} 
    {% if user == topic.author %}
    <form action="{% url 'homepage:new_entry' topic.id %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>
    </form>
    {% else %}
    <p>You are not allowed here </p>
    {% endif %} 
{% else %}
    <p>You are not logged it </p>
    <p>You may Sign In <a href="{% url 'users:signin' %}">here</a> or Sign Up <a href="{% url 'users:signup' %}">here</a></p>
{% endif %}



{% endblock content %}

homepage/templates/homepage/postform.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add a topic{% endblock title %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">Blogger</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
          Add a Topic 
    </div>
  </nav>
{% endblock header %}

{% block content %}


{% if user.is_authenticated %}

<form action="{% url 'homepage:new_topic' %}" method="POST" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
</div>
<button type="button" class="btn btn-dark btn-lg">Create Topic</button>
    </form>
    
{% else %}

<p>You are not logged it </p>
<p>You may Sign In <a href="{% url 'users:signin' %}">here</a> or Sign Up <a href="{% url 'users:signup' %}">here</a></p>

{% endif %}

{% endblock content %}

users/templates/users/myprofile.html
{% extends 'homepage/base.html' %}

{% block title %} {{userprofile}} profile page {% endblock title %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">Blogger</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
<ul class="list-group">
    <li class="list-group-item list-group-item-dark" style="text-align: center;">{{userprofile}}</li>
</ul>

{% endblock header %}
{% block content %}
<ul class="list-group" style="text-align: center;">
    <li class="list-group-item">{{profiles.age}}</li>
    <li class="list-group-item">{{profiles}}</li>
    <li class="list-group-item">{{profiles.genre}}</li>
</ul>


    
{% if user.id == userprofile.id %}
<div class="list-group" style="text-align: center;">
    <a href="{% url 'users:profile' %}" class="list-group-item list-group-item-dark">Edit Profile</a>
</div>
{% else %}
    <a href="">Like Profile</a>
{% endif %}

{% endblock content %}

users/templates/users/profile.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update Profile{% endblock title %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">Blogger</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
{% endblock header %}
{% block content %}

    <form action="{% url 'users:profile' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="hidden" value="next">
        <button type="submit" class="btn btn-dark">Update Profile</button>
    </form>
    <div class="list-group" style="text-align: center;">
        <a href="{% url 'users:doneprofile' user.username%}" class="list-group-item list-group-item-dark">Next</a>
    </div>
{% endblock content %}

users/templates/users/signin.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Sign In {% endblock title %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">Blogger</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
</nav>
{% endblock header %}

{% block content %}

{% if form.errors %}
    <p>Error! Not able to sign in. Your password and username might not match</p>
{% endif %}

<form action="{% url 'users:signin' %}" method="POST" novalidate>
    {% csrf_token %}
    {{form|crispy}}
    <input type="hidden" value="next">
    <button type="submit" value="signin" class="btn btn-dark">Sign In</button>
</form>
<p>Don't have an account? Sign up <a href="{% url 'users:signup' %}">here</a></p>
    
{% endblock content %}

users/templates/users/signup.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block title %} homepage{% endblock title %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">Blogger</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
</nav>

{% endblock header %}
{% block content %}
    <form action="{% url 'users:signup' %}" method="POST" novalidate>
        {% csrf_token %}
        {{form|crispy}}
        <input type="hidden" value="next">
        <button type="submmit" value="signup" class="btn btn-dark">Sign Up</button>
    </form>
    <p>Have an account? Sign in <a href="{% url 'users:signin' %}">here</a></p>
{% endblock content %}

users/templates/users/success.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Sign Out Page {% endblock title %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">Blogger</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:signin' %}">Sign In</a>
        </li>
      </ul>
    </div>
  </nav>
    <p>Go back to homepage? <a href="{% url 'homepage:home' %}">Blogger</a></p>  
    <p><a href="{% url 'users:signin' %}">Sign in </a> again?</p>
{% endblock content %}